version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    container_name: 'mariadb_scim'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: springbootdb
    ports:
      - 3306:3306
